#!/usr/bin/env python3
"""
Adversarial DevSecOps: LLM Auto-Remediator (The Blue Team)
This script reads the exploits generated by the Genetic Algorithm,
injects them into a context-aware prompt along with the source code,
and asks the Gemini API to mathematically patch the vulnerability.
It then creates a local branch and applies the patch.
"""

import os
import json
import time
import subprocess
import requests
import google.generativeai as genai
from dotenv import load_dotenv

# Load environment variables (from .env)
load_dotenv()

# Configure Gemini API
API_KEY = os.getenv("GEMINI_API_KEY")
if not API_KEY:
    print("[!] GEMINI_API_KEY not found in environment variables. Exiting.")
    exit(1)

genai.configure(api_key=API_KEY)

# Use the best model available on the free tier for code generation
try:
    model = genai.GenerativeModel('gemini-2.5-flash')
except Exception as e:
    print(f"[!] Failed to initialize Gemini model: {e}")
    exit(1)

def get_source_code():
    """Reads the core application files to provide context to the LLM."""
    files_to_read = ['app.py', 'database.py']
    source_context = {}
    for file in files_to_read:
        if os.path.exists(file):
            with open(file, 'r', encoding='utf-8') as f:
                source_context[file] = f.read()
    return source_context

def remediate_vulnerability(finding):
    """Sends the context and payload to the LLM to get a JSON patch."""
    target = finding['target']
    vuln_type = finding['vulnerability_type']
    payload = finding['successful_payload']
    
    print(f"\n[*] Requesting AI Remediation for {vuln_type} on {target}...")
    source_code = get_source_code()
    
    # This is the "Payload-Driven Prompt Engineering" novelty
    prompt = f"""
    You are an expert DevSecOps Security Architect. The application was just successfully breached by a Genetic Algorithm fuzzer.
    
    Vulnerability Type: {vuln_type}
    Target Endpoint: {target}
    Successful Exploit Payload: {payload}
    
    This is the source code of the application:
    --- app.py ---
    {source_code.get('app.py', 'File not found.')}
    --- database.py ---
    {source_code.get('database.py', 'File not found.')}
    
    Analyze the code and find the root cause that allowed this specific payload to bypass the filters. 
    Rewrite the vulnerable functions using industry-standard secure coding practices (e.g., Parameterized Queries for SQLi, proper escaping for XSS). 
    Do NOT just write a regex filter for this exact string; fix the underlying architectural flaw so all future mutations fail.
    
    You must respond ONLY with a valid JSON object. Do NOT include markdown blocks like ```json around it.
    The JSON must exactly match this schema:
    {{
        "explanation": "A 1-sentence technical summary of the architectural fix.",
        "files_to_update": [
            {{
                "file_path": "database.py",
                "new_content": "the entirely rewritten, secure source code for the file"
            }}
        ]
    }}
    """
    
    try:
        response = model.generate_content(prompt)
        response_text = response.text.strip()
        
        # Clean up potential markdown formatting from LLM
        if response_text.startswith("```json"):
            response_text = response_text[7:]
        if response_text.startswith("```"):
            response_text = response_text[3:]
        if response_text.endswith("```"):
            response_text = response_text[:-3]
            
        patch_data = json.loads(response_text.strip())
        return patch_data
    except json.JSONDecodeError as e:
        print(f"[!] AI returned invalid JSON. The fix could not be parsed: {e}")
        # Print snippet of bad response for debugging
        print(f"Raw Output Snippet: {response_text[:200]}...")
        return None
    except Exception as e:
        print(f"[!] AI Remediation API Call Failed: {e}")
        return None

def apply_patch_and_commit(patch_data):
    """Applies the LLM's code modifications and commits them to the current branch."""
    if not patch_data:
        return
        
    print(f"\n[+] AI Architect's Explanation: {patch_data.get('explanation', 'No explanation provided.')}")
    
    # Apply changes securely
    allowed_files = ['app.py', 'database.py']
    files_patched = []
    
    for file_update in patch_data.get('files_to_update', []):
        file_path = file_update.get('file_path')
        new_content = file_update.get('new_content')
        
        # Security check: Only allow patching specific files
        if file_path in allowed_files and new_content:
            print(f"[*] Applying secure patch to {file_path}...")
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(new_content)
            files_patched.append(file_path)
        else:
            print(f"[!] Warning: AI attempted to patch unauthorized file '{file_path}'. Blocked.")
            
    if not files_patched:
        print("[!] No valid files were patched. Exiting.")
        return
        
    # Commit changes
    for f in files_patched:
        subprocess.run(["git", "add", f], check=False, capture_output=True)
    
    commit_msg = f"Security Patch (Auto-Remediation): {patch_data.get('explanation')}"
    subprocess.run(["git", "commit", "-m", commit_msg], check=False, capture_output=True)
    
    print("\n" + "=" * 60)
    print(f"[SUCCESS] Vulnerability fix committed successfully!")
    print("=" * 60)

def create_pull_request(branch_name, pr_title="Security Auto-Remediation Patch"):
    """Uses the GitHub API to automatically open a Pull Request."""
    github_token = os.getenv("GITHUB_TOKEN")
    if not github_token:
        print("\n[!] GITHUB_TOKEN not found in environment variables. Skipping automatic PR creation.")
        print("[*] To enable automatic PRs, add GITHUB_TOKEN to Jenkins or your .env file.")
        return
        
    print(f"\n[*] Opening Pull Request for branch '{branch_name}'...")
    url = "https://api.github.com/repos/Snehalgupta-07/GenePatch/pulls"
    headers = {
        "Authorization": f"token {github_token}",
        "Accept": "application/vnd.github.v3+json"
    }
    data = {
        "title": pr_title,
        "head": branch_name,
        "base": "main",
        "body": "### AI Auto-Remediation\n\nThe Genetic Algorithm Fuzzer discovered vulnerabilities in the `main` branch. The Blue Team LLM has mathematically analyzed the exploits and rewritten the vulnerable code to securely patch them.\n\nPlease review these changes before merging."
    }
    
    response = requests.post(url, headers=headers, json=data)
    if response.status_code == 201:
        pr_url = response.json().get("html_url")
        print(f"[SUCCESS] Pull Request created automatically: {pr_url}")
    else:
        print(f"[!] Failed to create PR. GitHub API responded with {response.status_code}: {response.text}")

def main():
    print("=" * 60)
    print("ADVERSARIAL AI BLUE TEAM: LLM AUTO-REMEDIATOR")
    print("=" * 60)
    
    report_path = 'reports/fuzzer_findings.json'
    if not os.path.exists(report_path):
        print("[-] No fuzzer findings found (report missing). Application appears secure.")
        return
        
    try:
        with open(report_path, 'r') as f:
            data = json.load(f)
    except json.JSONDecodeError:
        print("[!] Error reading fuzzer_findings.json. File is corrupt.")
        return
        
    findings = data.get('exploits', [])
    if not findings:
        print("[-] Report exists, but no exploits were logged. Application appears secure.")
        return
        
    print(f"[!] Detected {len(findings)} successful exploits from the Genetic Algorithm.")
    
    # Create a new local branch for all fixes
    branch_name = f"ai-patch-{int(time.time())}"
    print(f"[*] Checking out new local branch: {branch_name}")
    subprocess.run(["git", "checkout", "-b", branch_name], check=False, capture_output=True)
    
    # Loop through ALL findings and remediate them sequentially
    for i, target_finding in enumerate(findings):
        print(f"\n--- Processing Vulnerability {i+1}/{len(findings)} ---")
        patch_data = remediate_vulnerability(target_finding)
        apply_patch_and_commit(patch_data)
        
    print(f"\n[*] All fixes applied. Pushing branch '{branch_name}' to GitHub...")
    
    # Inject token into the remote URL to bypass the invisible password prompt in Jenkins
    github_token = os.getenv("GITHUB_TOKEN")
    if github_token:
        auth_url = f"https://oauth2:{github_token}@github.com/Snehalgupta-07/GenePatch.git"
        subprocess.run(["git", "remote", "set-url", "origin", auth_url], check=False, capture_output=True)
    
    subprocess.run(["git", "push", "-u", "origin", branch_name], check=False)
    
    # Trigger the automatic Pull Request
    create_pull_request(branch_name, pr_title=f"Security Patch: Automated Remediation ({len(findings)} fixes)")
    print("\n[*] Remediation workflow complete!")

if __name__ == "__main__":
    main()
