#!/usr/bin/env python3
"""
Adversarial DevSecOps: Autonomous Self-Healing Agent
This script represents a fully autonomous AI agent. It reads the exploits generated by the Fuzzer,
generates a patch, applies it locally, runs tests ON ITSELF, and loops if it fails.
"""

import os
import json
import time
import subprocess
import requests
import google.generativeai as genai
from dotenv import load_dotenv

# Load environment variables (from .env)
load_dotenv()

# Configure Gemini API
API_KEY = os.getenv("GEMINI_API_KEY")
if not API_KEY:
    print("[!] GEMINI_API_KEY not found in environment variables. Exiting.")
    exit(1)

genai.configure(api_key=API_KEY)

# Standard model for free tier
try:
    model = genai.GenerativeModel('gemini-2.5-flash')
except Exception as e:
    print(f"[!] Failed to initialize Gemini model: {e}")
    exit(1)

def get_source_code():
    """Reads the core application files to provide context to the LLM."""
    files_to_read = ['app.py', 'database.py']
    source_context = {}
    for file in files_to_read:
        if os.path.exists(file):
            with open(file, 'r', encoding='utf-8') as f:
                source_context[file] = f.read()
    return source_context

def remediate_vulnerability(finding, previous_errors=""):
    """Sends the context and payload to the LLM to get a JSON patch."""
    target = finding['target']
    vuln_type = finding['vulnerability_type']
    payload = finding['successful_payload']
    
    print(f"\n[*] Requesting AI Patch generation for {vuln_type}...")
    source_code = get_source_code()
    
    prompt = f"""
    You are an expert DevSecOps Security Architect. The application was just successfully breached by a fuzzer.
    
    Vulnerability Type: {vuln_type}
    Target Endpoint: {target}
    Successful Exploit Payload: {payload}
    
    This is the source code of the application:
    --- app.py ---
    {source_code.get('app.py', 'File not found.')}
    --- database.py ---
    {source_code.get('database.py', 'File not found.')}
    
    Analyze the code and rewrite the vulnerable functions securely. 
    Use industry-standard secure coding practices (e.g., Parameterized Queries for SQLi, proper werkzeug.security imports).
    """
    
    # THE SELF-HEALING FEEDBACK INJECTION
    if previous_errors:
        prompt += f"""
        
        [CRITICAL FEEDBACK FROM YOUR PREVIOUS ATTEMPT]:
        Your last patch failed verification! Here is the error log from the CI/CD pipeline:
        
        {previous_errors}
        
        You MUST fix this specific error in your new patch. Do not repeat the same mistake.
        """
        
    prompt += """
    You must respond ONLY with a valid JSON object. Do NOT include markdown blocks like ```json around it.
    The JSON must exactly match this schema:
    {
        "explanation": "A 1-sentence technical summary of the architectural fix.",
        "files_to_update": [
            {
                "file_path": "app.py",
                "new_content": "the entirely rewritten, secure source code for the file"
            }
        ]
    }
    """
    
    try:
        response = model.generate_content(prompt)
        response_text = response.text.strip()
        
        if response_text.startswith("```json"):
            response_text = response_text[7:]
        if response_text.startswith("```"):
            response_text = response_text[3:]
        if response_text.endswith("```"):
            response_text = response_text[:-3]
            
        return json.loads(response_text.strip())
    except Exception as e:
        print(f"[!] AI failed to generate valid JSON patch: {e}")
        return None

def apply_patch_and_commit(patch_data):
    """Applies the LLM's code modifications and commits them locally."""
    if not patch_data:
        return False
        
    print(f"[+] AI Explanation: {patch_data.get('explanation', '')}")
    
    allowed_files = ['app.py', 'database.py']
    files_patched = []
    
    for file_update in patch_data.get('files_to_update', []):
        file_path = file_update.get('file_path')
        new_content = file_update.get('new_content')
        
        if file_path in allowed_files and new_content:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(new_content)
            files_patched.append(file_path)
            
    if not files_patched:
        return False
        
    for f in files_patched:
        subprocess.run(["git", "add", f], check=False, capture_output=True)
    
    commit_msg = f"Security Patch: {patch_data.get('explanation')}"
    subprocess.run(["git", "commit", "-m", commit_msg], check=False, capture_output=True)
    return True

def create_pull_request(branch_name, pr_title="Security Auto-Remediation Patch"):
    """Uses the GitHub API to automatically open a Pull Request."""
    github_token = os.getenv("GITHUB_TOKEN")
    if not github_token:
        print("\n[!] GITHUB_TOKEN not found in environment variables. Skipping PR creation.")
        return
        
    print(f"\n[*] Opening Pull Request for branch '{branch_name}'...")
    url = "https://api.github.com/repos/Snehalgupta-07/GenePatch/pulls"
    headers = {
        "Authorization": f"token {github_token}",
        "Accept": "application/vnd.github.v3+json"
    }
    data = {
        "title": pr_title,
        "head": branch_name,
        "base": "main",
        "body": "### AI Auto-Remediation (Self-Verified)\n\nThe AI Agent mathematically analyzed the vulnerability, wrote a patch, ran Pytest against it, and ran the Fuzzer against it locally.\n\nAll tests passed successfully before this PR was opened!"
    }
    
    response = requests.post(url, headers=headers, json=data)
    if response.status_code == 201:
        print(f"[SUCCESS] Pull Request created automatically: {response.json().get('html_url')}")
    else:
        print(f"[!] Failed to create PR: {response.text}")

def main():
    print("=" * 60)
    print("ADVERSARIAL AI: AUTONOMOUS SELF-HEALING AGENT")
    print("=" * 60)
    
    report_path = 'reports/fuzzer_findings.json'
    if not os.path.exists(report_path):
        print("[-] No fuzzer findings found. Application appears secure.")
        return
        
    try:
        with open(report_path, 'r') as f:
            data = json.load(f)
    except Exception:
        print("[!] Error reading fuzzer_findings.json.")
        return
        
    findings = data.get('exploits', [])
    if not findings:
        return
        
    print(f"[!] Target Acquired: {len(findings)} exploits found.")
    
    # TO CONSERVE TOKENS: We will only self-heal the #1 highest priority vulnerability
    target_finding = findings[0]
    vuln_type = target_finding['vulnerability_type']
    print(f"[*] Agent focusing solely on top priority: {vuln_type}")
    
    subprocess.run(["git", "config", "user.email", "ai-blue-team@genepatch.local"], check=False)
    subprocess.run(["git", "config", "user.name", "AI Agent"], check=False)
    
    branch_name = f"ai-patch-{int(time.time())}"
    subprocess.run(["git", "checkout", "-b", branch_name], check=False, capture_output=True)
    
    MAX_RETRIES = 2
    previous_errors = ""
    success = False
    
    for attempt in range(MAX_RETRIES):
        print(f"\n--- Healing Attempt {attempt+1}/{MAX_RETRIES} ---")
        
        # 1. Generate & Apply
        patch_data = remediate_vulnerability(target_finding, previous_errors)
        if not apply_patch_and_commit(patch_data):
            print("[!] Failed to apply patch.")
            time.sleep(3)
            continue
            
        # 2. Gate 1: Functional Verification
        print("[*] Gate 1: Running Functional Verification (Pytest)...")
        pytest_proc = subprocess.run(["venv\\Scripts\\pytest.exe", "test_functional.py", "-v"], capture_output=True, text=True)
        
        if pytest_proc.returncode != 0:
            print(f"\n========== PYTEST OUTPUT ==========\n{pytest_proc.stdout}\n===================================")
            print("[!] FAILURE: The AI's patch broke the application syntax/functionality.")
            print("[*] Capturing Pytest traceback for feedback loop...")
            previous_errors = f"Your last patch introduced a bug. Pytest failed with this traceback:\n{pytest_proc.stdout[-800:]}"
            subprocess.run(["git", "reset", "--hard", "HEAD~1"], check=False, capture_output=True)
            time.sleep(5) # Wait out rate limits
            continue
        else:
            print(f"\n========== PYTEST OUTPUT ==========\n{pytest_proc.stdout}\n===================================")
            
        # 3. Gate 2: Security Verification
        print("[*] Gate 2: Running Security Verification (Fuzzer)...")
        # Ensure fresh database schema
        if os.path.exists('vulnerable_app.db'):
            try:
                os.remove('vulnerable_app.db')
            except Exception:
                pass
        server_proc = subprocess.Popen(["venv\\Scripts\\python.exe", "app.py"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        time.sleep(3) # Wait for Flask to boot
        
        fuzzer_proc = subprocess.run(["venv\\Scripts\\python.exe", "ga_fuzzer.py"], capture_output=True, text=True)
        server_proc.terminate()
        
        if fuzzer_proc.returncode != 0:
            print(f"\n========== FUZZER OUTPUT ==========\n{fuzzer_proc.stdout}\n===================================")
            print("[!] FAILURE: The AI's patch did not actually fix the vulnerability.")
            print("[*] Capturing Fuzzer report for feedback loop...")
            previous_errors = "Your last patch was invalid. The genetic fuzzer still successfully exploited the endpoint. You must try a completely different architectural approach."
            subprocess.run(["git", "reset", "--hard", "HEAD~1"], check=False, capture_output=True)
            time.sleep(5)
            continue
        else:
            print(f"\n========== FUZZER OUTPUT ==========\n{fuzzer_proc.stdout}\n===================================")
            
        print("\n[SUCCESS] The AI Patch mathematically passed all Functional and Security gates!")
        success = True
        break
        
    if success:
        print(f"\n[*] Pushing verified branch '{branch_name}' to GitHub...")
        github_token = os.getenv("GITHUB_TOKEN")
        if github_token:
            auth_url = f"https://oauth2:{github_token}@github.com/Snehalgupta-07/GenePatch.git"
            subprocess.run(["git", "remote", "set-url", "origin", auth_url], check=False, capture_output=True)
        
        subprocess.run(["git", "push", "-u", "origin", branch_name], check=False)
        create_pull_request(branch_name, pr_title=f"Security Patch: {vuln_type} (Self-Verified)")
    else:
        print("\n[!] Agent exhausted all retries and could not create a perfect patch. Aborting.")
        subprocess.run(["git", "checkout", "main"], check=False, capture_output=True)
        subprocess.run(["git", "branch", "-D", branch_name], check=False, capture_output=True)

if __name__ == "__main__":
    main()
